apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{.repoName}}
spec:
  provider: gcp
  parameters:
    auth: provider-adc
    secrets: |
      - resourceName: "projects/loupe-dev/secrets/credentials_sentry/versions/latest"
        fileName: "credentials_sentry.yaml"
