apiVersion: v1
kind: Service
metadata:
  name: {{.repoName}}
  labels:
    app: {{.repoName}}
    version: v2
spec:
  selector:
    app: {{.repoName}}
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc-server
